syntax = "proto3";

package user;

service AuthService {
  rpc Signup(SignupRequest) returns (SignupResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc verifyUser(verifyUserRequest) returns (VerifyUserResponse);
  rpc Logout(LogoutRequest) returns (GenericResponse);
  rpc RequestPasswordReset(ResetRequest) returns (RequestResetResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  rpc ChangePassword(ChangePasswordRequest) returns (GenericResponse);
  rpc googleOAuthCallback(GoogleAuthRequest) returns (GoogleAuthResponse);
}

service UserService {
  rpc GetProfile(GetUserRequest) returns (UserProfileResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UserProfileResponse);
  rpc DeleteAccount(DeleteRequest) returns (GenericResponse);
}

service SubscriptionService {
  rpc CheckSubscription (CheckSubscriptionRequest) returns (CheckSubscriptionResponse);
  rpc SubscriptionWebHook (WebhookRequest) returns (WebhookResponse);
  rpc CancelSubscription (CancelRequest) returns (GenericResponse);
}

message UserStruct {
  string id = 1;
  string name = 2;
  string email = 3;
}

message SignupRequest { string email = 1; string password = 2; string name = 3; }
message LoginRequest { string email = 1; string password = 2; }
message verifyUserRequest { string sessionCookie = 1; }
message LogoutRequest { string userId = 1; }
message ChangePasswordRequest { string userId = 1; string oldPassword = 2; string newPassword = 3; }
message GoogleAuthRequest {
    string googleId = 1; 
    string email = 2;
    string name = 3;
    string profilePicture = 4;
}

message ResetRequest { string email = 1; }
message ResetPasswordRequest { string resetToken = 1; string newPassword = 2; }

message GetUserRequest { string userId = 1; }
message UpdateProfileRequest { string userId = 1; string name = 2; string email = 3; }
message DeleteRequest { string userId = 1; }

message CancelRequest { string userId = 1;}

message GenericResponse { 
    string message = 1;
}

message SignupResponse {
    string userData = 1;
    string sessionCookie = 2;
}
message GoogleAuthResponse {
  string userData = 1;
  string sessionCookie = 2;
}

message LoginResponse {
    string userData = 1;
    string sessionCookie = 2;
}

message VerifyUserResponse {
    UserStruct userData = 2;
    string sessionCookie = 3;
}

message RequestResetResponse {
    string resetToken = 1;
}

message ResetPasswordResponse {
    string status = 1;
    string sessionCookie = 2;
}

message UserProfileResponse {
    string userData = 1;
}

message CheckSubscriptionRequest {
  string userId = 1;
  string plan = 2;
}

message CheckSubscriptionResponse {
  string url = 1;
}

message WebhookRequest {
  string signature = 1;
  bytes body = 2;
}

message WebhookResponse {
  bool received = 1;
}