syntax = "proto3";

package ocr;

import "google/protobuf/empty.proto";

service OcrService {
  rpc CountFiles (google.protobuf.Empty) returns (CountResponse);
  rpc AnalyzeFile (AnalyzeRequest) returns (AnalyzeResponse);
  rpc AnalyzeSubscription (AnalyzeSubscriptionRequest) returns (AnalyzeSubscriptionResponse);
  rpc ProcessFile (ProcessRequest) returns (ProcessResponse);
  rpc RefundCall (RefundRequest) returns (google.protobuf.Empty);
  rpc GetDoc (GetDocRequest) returns (GetDocResponse);
  rpc GetAllDocs (GetAllDocsRequest) returns (GetAllDocsResponse);
  rpc GetHistory (GetHistoryRequest) returns (GetHistoryResponse);
}

message FileItem {
  string path = 1;
  string mimetype = 2;
}

message CountResponse {
  bool halt = 1; 
}

message AnalyzeRequest { 
  repeated FileItem files = 1; 
}

message AnalyzeResponse { 
  int32 totalPages = 1;
  repeated FileItem processedFiles = 2;
}

message ProcessRequest { 
  string userId = 1;     
  repeated FileItem files = 2; 
}

message ProcessResponse { 
  string batchId = 1;      
}

message AnalyzeSubscriptionRequest {
  string userId = 1;
  int32 cost = 2;
}

message AnalyzeSubscriptionResponse {
  bool success = 1;
  int32 remainingCredits = 2;
}

message RefundRequest {
  string userId = 1;
  int32 amount = 2;
}

message GetDocRequest {
  string batchId = 1;
  string userId = 2;
}

message GetDocResponse {
  string docData = 1;
}

message GetAllDocsRequest {
  string userId = 1;
}

message GetAllDocsResponse {
  string docsData = 1; 
}

message GetHistoryRequest {
  string userId = 1;
}

message GetHistoryResponse {
  string docsData = 1;
}